openapi: 3.0.3
info:
  title: Cadastro
  description: "Cadastro"
  version: 1.0.0
tags:
  - name: cadastroController
    description: Sistema de cadastro
paths:
  /v1/cadastrar:
    post:
      tags:
        - cadastrar-controller
      description: enviar cadastro
      operationId: enviarCadastro
      requestBody:
        description: enviar cadastro
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/enviarCadastro'
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
        '405':
          description: Validation exception
      security:
        - basicAuth: []

components:
  schemas:
    enviarCadastro:
      title: enviarCadastro
      type: object
      required:
        - nome
        - cpf
        - anoNascimento
      properties:
        nome:
          type: string
        cpf:
          type: string
          pattern: '^\d{3}\.\d{3}\.\d{3}-\d{2}$'
        anoNascimento:
          type: string
          pattern: '^\d{4}/\d{2}/\d{2}$'
        profissao:
          type: string
        telefone:
          type: string
        endereco:
          type: string
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
